config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :types
  resources :products
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"home#index"
  get "/categories/:id", to:"categories#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products,dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
    before_create {|product| product.title = product.title.capitalize}
    has_one_attached :image
    belongs_to :category, optional: true
    has_many :types,dependent: :destroy
    validates :sku, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/}
    validates :title, presence: true, format: {with: /\A(?:[A-Za-z]+)(?:[A-Za-z0-9 _]*)\z/}
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0}
    validates :quantity , format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0}
    accepts_nested_attributes_for :types


    def self.search(search)
        if search
            where('title  LIKE ?', "%#{search}%")
        else
            all
        end
    end
end

app/models/property.rb
class Property < ApplicationRecord

    belongs_to :type, optional: true
end

app/models/type.rb
class Type < ApplicationRecord
    belongs_to :product, optional: true
    has_many :properties, dependent: :destroy
    has_one_attached :image 
    accepts_nested_attributes_for :properties
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
    after_save  :check_user
    validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
    validates :password, presence: true, confirmation: { case_sensitive: true }, length: { minimum: 6}
    validates :phone, presence: true, uniqueness: true, format: { with: /\A\d{9}\z/}
    
    def check_user
        pass_hash = BCrypt::Password.create(password)
        update_columns(password: pass_hash, password_confirmation: pass_hash)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: %i[show]
    def show 
    end


    private
      def set_category
        @category = Category.find(params[:id])
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.search(params[:search]).paginate(:page => params[:page], :per_page => 3).order("created_at DESC")
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:sku, :title, :price, :quantity, :image, :category_id, types_attributes: [:id,:type_name, :image, properties_attributes: [:id,:value, :in_stock]])
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:value, :in_stock)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: "Type was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: "Type was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:type_name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   add_flash_types :success, :danger, :warning, :info

   def new
      @user = User.new
   end


   def create
      @user = User.new(user_params)
      if @user.save
         redirect_to root_path
         flash[:success] = "Sign up was successfully!"
      else
         respond_to do |format|
            format.html { render :new ,status: :unprocessable_entity}
         end
      end
   end


    private
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :birthday, :phone)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/show.html.erb
<h1><%= @category.name%></h1>
<h3>List product : </h3>
<% @category.products.each do |product| %>
  <li><%= link_to "#{product.title}","/products/#{product.id}"%></li>
<%end%>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home",root_path,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Add product",new_product_path,class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Products",products_path,class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up",new_user_path,class:"nav-link"%>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Category.all.each do |category|%>
           <%= link_to "#{category.name}", "/categories/#{category.id}",class:"dropdown-item"%>
          <%end%>
        </div>
      </li>
    </ul>
    <%= form_tag(products_path, :method => "get") do %>
     <%= text_field_tag :search, params[:search], placeholder: "Search products" %>
      <%= submit_tag "Search",class:"btn btn-outline-success my-2 my-sm-0" %>
       <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

     <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <%= render "home/header"%>
    <div class="container">
     <% flash.each do |key, value| %>
        <div id="flash" class="alert alert-<%= key %>">
          <%= sanitize(value) %>
          <a href="#" data-dismiss="alert">×</a>
        </div>
     <% end %>
    </div>
    <%= yield %>
  <script type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
       $('#flash').remove();
      }, 10000);
    })
  </script>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for product do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :sku %>
    <%= form.text_field :sku, class:"form-control" %>
  </div>
   <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
   <div class="field form-group">
    <%= form.label :Category %>
    <%= form.collection_select :category_id, Category.all, :id, :name , class:"form-control" %>
  </div>
  
   <div id="types">
     <%= form.fields_for :types do |type|%>
        <%= render "types_fields", form: type%>
     <%end%>
     <div class="field form-group">
        <%= link_to_add_association 'add type', form, :types, form_name: 'form',  partial: 'types_fields', class:"btn btn-info"%>
     </div>
   </div>  


  <div class="field form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>
<div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control" %>
</div>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/products/_properties_fields.html.erb
<div class="nested-fields">
<div class="field form-group">
  <%= form.label :value %>
  <%= form.text_field :value,class:"form-control" %>
  </div>
<div class="field form-group">
  <%= form.label "in stock" %>
  <%= form.number_field :in_stock,class:"form-control" %>
</div>
<div class="field form-group">
  <%= link_to_remove_association "Remove property", form,class:"btn btn-dark" %>
</div>
</div>

app/views/products/_types_fields.html.erb
<div class="nested-fields">
<div class="field form-group">
  <%= form.label :type %>
  <%= form.text_field :type_name,class:"form-control" %>
</div>

    <div id="properties">
      <%= form.fields_for :properties do |property|%>
          <%= render "properties_fields", form: property%>
      <%end%>
      <div class="field form-group">
          <%= link_to_add_association 'Add property', form, :properties, form_name: 'form',   partial: 'properties_fields',class:"btn btn-info"%>
      </div>
    </div>
<div class="field form-group">
  <%= link_to_remove_association "Remove type", form, class:"btn btn-dark" %>
<div>
<div class="field form-group">
    <%= form.label "Detail image" %>
    <%= form.file_field :image, class:"form-control" %>
</div>
</div>

app/views/products/edit.html.erb
<div class="container">
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Sku</th>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= image_tag(product.image) if product.image.present? %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
<div class="pagination">
<%= will_paginate @products, :renderer => BootstrapPagination::Rails %>

</div>

app/views/products/new.html.erb
<div class="container">
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>
<p>
   <strong>Type:</strong>
   <% @product.types.each do |type|%>
     <li> <%= type.type_name%></li>
     <%= image_tag(type.image) if type.image.present?%>
      <%type.properties.each do |property|%>
         <p>Value : <%= property.value%></p>
         <p>In stock :<%= property.in_stock%></p>
      <%end%>
   <%end%>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :in_stock %>
    <%= form.number_field :in_stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>In stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.value %></td>
        <td><%= property.in_stock %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @property.value %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @property.in_stock %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/types/_form.html.erb
<%= form_with(model: type) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
        <% type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_name %>
    <%= form.text_field :type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Type name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.type_name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type name:</strong>
  <%= @type.type_name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/users/new.html.erb
<div class ="container">
<%= form_for @user do |form|%>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %></h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field form-group">
    <%= form.label :Email %>
    <%= form.text_field :email, placeholder: "example@mail.com" , class:"form-control" %>
</div>
<div class="field form-group">
    <%= form.label :Password%>
    <%= form.password_field :password , placeholder: "Password at least six characters", class:"form-control"%>
</div>
<div class="field form-group">
     <%= form.label "Confirm password"%>
    <%= form.password_field :password_confirmation, placeholder: "Confirm", class:"form-control"%>
</div>
<div class="field form-group">
    <%= form.label :Birthday%>
    <%= form.date_field :birthday, class:"form-control"%>
</div>
<div class="field form-group">
    <%= form.label :Phone%>
    <%= form.text_field :phone, placeholder: "Your phone" , class:"form-control"%>
</div>
<div class= "actions">
    <%= form.submit "Sign up",  class:"btn btn-primary"%>
</div>
<%end%>
</div>